name: Hero Self-Nomination
description: Use this form to nominate yourself to Hero status in the program
title: "[Nomination] : "
labels: ["nomination", "heroes"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out your self-nomination to Hero status in the program! A Hero is someone who is actively advocating for the technology of the Polkadot ecosystem, including building independent Substrate chains, ink! development, building Polkadot-related tooling, etc., effectively spreading awareness and educating a broader audience about the technology.
  - type: markdown
    attributes:
      value: |
        Please fill out each section to the best of your ability. The more you are able to share the better our team is able to evaluate your self-nomination. For most questions we will be happy to see link(s), directing us to the right source of information for proof of your achievements.
  - type: textarea
    id: code-contribution-polkadot-sdk
    attributes:
      label: Code contribution to the Polkadot SDK repository
      description: Share with us the links to GitHub repos where you have been a code contributor for more than one instance to a merged pull request to the Polkadot SDK repository (Polkadot, Substrate, Cumulus) in the past quarter.
      placeholder: Add links to your code contribution(s) here.
  - type: textarea
    id: code-contribution-chain-project
    attributes:
      label: Code contribution to a Substrate-based chain project
      description: Share with us the links to GitHub repos where you have been a code contributor for more than one instance to an open-source Substrate-based chain project in the past quarter.
      placeholder: Add links to your code contribution(s) here.
  - type: textarea
    id: code-contribution-tool-library
    attributes:
      label: Code contribution to a tool or library
      description: Share with us the links to GitHub repos where you have been a code contributor for more than one instance to a popular open-source library or tool used within the Polkadot ecosystem in the past quarter.
      placeholder: Add links to your code contribution(s) here.
  - type: textarea
    id: code-contribution-dapp
    attributes:
      label: Code contribution to a dapp
      description: Share with us the links to GitHub repos where you have been a code contributor for more than one instance to a dapp within the Polkadot ecosystem in the past quarter.
      placeholder: Add links to your code contribution(s) here.  
  - type: textarea
    id: project-ownership
    attributes:
      label: Owned or maintained project(s)
      description: Share with us link(s) to any other open source Polkadot ecosystem project(s) that you own or maintain.
      placeholder: Add links to your project(s) here.
  - type: textarea
    id: technical-education
    attributes:
      label: Coding workshops or training sessions 
      description: Share with us links to events if you have taught a coding workshop or training session on Polkadot and/or Rust in the past quarter. 
      placeholder: Add links to event(s) here.
  - type: textarea
    id: documentation-contribution
    attributes:
      label: Contribution to documentation
      description: Share with us links to GitHub repos where you have been contributing more than once to the documentation within the Polkadot ecosystem in the past quarter. 
      placeholder: Add links to your contribution(s) here.
  - type: textarea
    id: research-publication
    attributes:
      label: R&D
      description: Share with us link(s) if you have published a technical research paper or article about Rust or Polkadot with more than 60% of your content.
      placeholder: Add links to your publication(s) here.
  - type: textarea
    id: stackexchange-profile
    attributes:
      label: StackExchange profile 
      description: Share with us the link to your StackExchange profile. 
      placeholder: Add links to your profile here.
  - type: textarea
    id: polkadot-forum-activity
    attributes:
      label: Activity on the Polkadot forum
      description: | 
        Share with us the link to your Polkadot forum profile. We are going to look at the followings:
          Your authored forum posts in the past quarter.
          Your comments to topics on the forum in the past quarter.
          We are also looking for any technical topics that you started or technical responses you gave to 3 or more topics in the Tech talk section of the forum in the past quarter. 
      placeholder: Add links to your forum profile here.
  - type: textarea
    id: event-attendance-polkadot-events
    attributes:
      label: Attendance at Polkadot-related events 
      description: Share with us the link(s) to any Polkadot-related event(s) that you attended in the past quarter (excluding sub0, Decoded and hackathons).
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: event-attendance-sub0
    attributes:
      label: Attendance at sub0 
      description: Share with us the link(s) and the year of the latest sub0 you attended in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: event-attendance-decoded
    attributes:
      label: Attendance at Polkadot Decoded 
      description: Share with us the link(s) and the year of the latest Polkadot Decoded you attended in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: hackathon-participation
    attributes:
      label: Participation at a Polkadot hackathon (Polkadot-focused or has a Polkadot track)
      description: Share with us the link(s) to hackathon(s) that you participated at with a submitted project in the past quarter. Please also share link(s) to your submitted project(s).
      placeholder: Add links to the hackathon(s) and your project(s) here.
  - type: textarea
    id: hackathon-participation-won-project
    attributes:
      label: Participation at a Polkadot hackathon (Polkadot-focused or has a Polkadot track)
      description: Share with us the link(s) to hackathon(s) where you won with a submitted project in the past quarter. Please also share link(s) to your submitted project(s).
      placeholder: Add links to the hackathon(s) and your project(s) here.
  - type: textarea
    id: heroes-mentoring
    attributes:
      label: Mentoring within the Heroes program
      description: Share with us the (user)name to the folk(s) you are or have been mentoring within the Polkadot Developer Heroes program. 
      placeholder: Add the (user)name(s) here.
  - type: dropdown
    id: ambassador-program
    attributes:
      label: Polkadot Ambassador Program
      description: Are you a Polkadot Ambassador?
      options:
        - "Yes, I'm a Polkadot Ambassador"
        - "Yes, I'm a Polkadot Senior or Head Ambassador"
        - "No, I'm not a Polkadot Ambassador"
  - type: textarea
    id: community-moderation
    attributes:
      label: Community moderation
      description: Share with us your username and the channel(s) if you are a moderator or active contributor in Polkadot-focused online communities (e.g., Telegram, Discord). 
      placeholder: Add the (user)name(s) and channel names here.
  - type: textarea
    id: written-content-blog
    attributes:
      label: Technical blog posts
      description: Share with us the link(s) to any technical blog post(s) that you have produced or contributed to in the past quarter.
      placeholder: Add links to the blog post(s).
  - type: textarea
    id: written-content-edu-content
    attributes:
      label: Interactive educational content
      description: Share with us the link(s) to any interactive educational content (e.g. coding challenges, quizzes) related to Polkadot that you have produced or contributed to in the past quarter.
      placeholder: Add links to the content(s).
  - type: textarea
    id: written-content-not-english
    attributes:
      label: International education content
      description: Share with us the link(s) to any Polkadot-related educational content in other languages than English that you have produced or contributed to in the past quarter.
      placeholder: Add links to the content(s).
  - type: textarea
    id: written-content-visual
    attributes:
      label: Visual content
      description: Share with us the link(s) to any Polkadot-related infographics or visual content that you have produced or contributed to in the past quarter.
      placeholder: Add links to the content(s).
  - type: textarea
    id: recorded-content-own
    attributes:
      label: Recorded own content
      description: Share with us the link(s) to any of your own Youtube (or other) or podcast channel that you have produced or contributed to with more than one technical-focused content in the past quarter. 
      placeholder: Add links to Youtube or podcast channel(s) here.
  - type: textarea
    id: recorded-content-guest
    attributes:
      label: Recorded content as a guest
      description: Share with us the link(s) to any Polkadot-focused YouTube (or other) channel or podcast that you have been invited to as a guest speaker in the past quarter.
      placeholder: Add links to Youtube or podcast channel(s) here.
  - type: textarea
    id: public-speaking
    attributes:
      label: Public speaking
      description: Share with us the link(s) to any occasions when you served as a speaker or panelist at conferences or events on Polkadot-related topic(s) in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: event-organization-meetup
    attributes:
      label: Organization of or participation at Polkadot-related technical community meetup
      description: Share with us the link(s) to any Polkadot related technical community meetup(s) that you organized or hosted in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: event-organization-workshop
    attributes:
      label: Organization of or participation at Polkadot-related technical community meetups
      description: Share with us the link(s) to any Polkadot related technical workshop that you organized or hosted in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: event-organization
    attributes:
      label: Organization of or participation at Polkadot-related technical workshops
      description: Share with us the link(s) to any Polkadot related technical workshop that you organized or hosted in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: event-organization-other
    attributes:
      label: Organization of or participation at Polkadot-related technical workshops
      description: Share with us the link(s) to any other community initiatives (eg. Polkadot-focused hackathon or coding challenge) that you organized or hosted in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: event-organization-judging
    attributes:
      label: Judging or mentoring a hackathon
      description: Share with us the link(s) to any Polkadot hackathons where you served as a judge or mentor at Polkadot hackathons in the past quarter.
      placeholder: Add links to the event(s) here.
  - type: textarea
    id: active-involvement-groups
    attributes:
      label: Active involvement in Polkadot related groups
      description: Share with us the link(s) if you have founded or you are leading any Polkadot-related working groups or special interest groups. 
      placeholder: Add links to group(s) here.
  - type: textarea
    id: active-involvement-engineering
    attributes:
      label: Leading engineering in Polkadot based projects
      description: Share with us the link(s) to any Polkadot-based project where you are holding an engineering leadership position.  
      placeholder: Add links to the project(s) here.
  - type: textarea
    id: online-discussions
    attributes:
      label: Leading discussions in the online space
      description: Share with us link(s) to any channels in the online space where you are running and/or managing a Polkadot-focused media outlet or publication. 
      placeholder: Add links to your publication(s) here.
