name: Hero Self-Nomination
description: Use this form to nominate yourself to Hero status in the program
title: "[Nomination] : "
labels: ["nomination", "heroes"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out your self-nomination to Hero status in the program! A Hero is someone who is actively advocating for the technology of the Polkadot ecosystem, including building independent Substrate chains, ink! development, building Polkadot-related tooling, etc., effectively spreading awareness and educating a broader audience about the technology.
  - type: markdown
    attributes:
      value: |
        Please fill out each section to the best of your ability. The more you are able to share the better our team is able to evaluate your self-nomination. For most questions we will be happy to see link(s), directing us to the right source of information for proof of your achievements.
  - type: textarea
    id: code-contribution
    attributes:
      label: Code contributions
      description: Share with us your substantial code contributions where your pull request has been merged to one or more of the followings.\n       - The Polkadot SDK repository (Polkadot, Substrate, Cumulus).\n       - Any open-source Substrate based chain project\n       - Any popular open-source library or tool used within the Polkadot ecosystem (eg. libp2p, rust, WASM,...)\n       - Any dapp within the Polkadot ecosystem.\n Please share links to everything referenced. If it's not an open source project, please reach out to us separately.
      placeholder: Add links to your code contributions here.
    validations:
      required: true
  - type: textarea
    id: project-ownership
    attributes:
      label: Owned or maintained project(s)
      description: Share with us link(s) to any other open source Polkadot ecosystem project(s) that you own or maintain.
      placeholder: Add links to your project(s) here.
    validations:
      required: true
  - type: textarea
    id: technical-education
    attributes:
      label: Technical education experience
      description: Share with us event or GH link(s) to the followings, if you have experience with them.\n      - Coding workshop(s) or training session(s) on Polkadot and/or Rust in the past quarter\n      - More than one contribution to documentation for Polkadot or a Polkadot ecosystem project in the past quarter.\n      - Publication of a technical research paper or article about Rust or Polkadot with more than 60% of own content.\n      - Your StackExchange profile. 
      placeholder: Add links to your past works here.
    validations:
      required: true
  - type: textarea
    id: polkadot-forum-activity
    attributes:
      label: Activity on the Polkadot forum
      description: Share with us the link to your Polkadot forum profile so we can look at the followings. \n      - Your authored forum posts in the past quarter.\n      - Your comments to topics on the forum in the past quarter.\n      We are also looking for any technical topics that you started or contributed to with responses in the past quarter. 
      placeholder: Add links to your forum profile here.
    validations:
      required: true
  - type: textarea
    id: event-attendance
    attributes:
      label: Attendance at Polkadot-related events 
      description: Share with us the link(s) to event(s) that you attended in the past quarter.\n      - Any Polkadot-related events.\n      - Most recent sub0 attended. \n      - Most recent Decoded attended.
      placeholder: Add links to the events here.
    validations:
      required: true
  - type: textarea
    id: hackathon-participation
    attributes:
      label: Participation at a Polkadot hackathon (Polkadot-focused or has a Polkadot track)
      description: Share with us the link(s) to hackathon(s) that you participated at in the past quarter.\n      - Any participation at a hackathon with a submitted project.\n      - Any hackathons you won with a submitted project. \n  Please provide us with link(s) to the hackathon and also to your submitted project(s).
      placeholder: Add links to the hackathon(s) and your project(s) here.
    validations:
      required: true
  - type: textarea
    id: heroes-mentoring
    attributes:
      label: Mentoring within the Heroes program
      description: Share with us the (user)name to the folk(s) you are or have been mentoring within the Polkadot Developer Heroes program. 
      placeholder: Add the (user)name(s) here.
    validations:
      required: true
  - type: dropdown
    id: ambassador-program
    attributes:
      label: Polkadot Ambassador Program
      description: Are you a Polkadot Ambassador?
      options:
        - "Yes, I'm a Polkadot Ambassador"
        - "Yes, I'm a Polkadot Senior or Head Ambassador"
        - "No, I'm not a Polkadot Ambassador"
  - type: textarea
    id: community-moderation
    attributes:
      label: Community moderation
      description: Share with us your username and the channel(s) if you are a moderator or active contributor in Polkadot-focused online communities (e.g., Telegram, Discord). 
      placeholder: Add the (user)name(s) and channel names here.
    validations:
      required: true
  - type: textarea
    id: written-content
    attributes:
      label: Written content in the past quarter
      description: Share with us the link(s) to any blog(s) where you have produced or contributed to any of the followings in the past quarter. \n      - More than one technical blog posts. \n      - Any interactive educational content (e.g. coding challenges, quizzes) related to Polkadot.\n      - Any Polkadot-related educational content in other languages than English.\n      - Any Polkadot-related infographics or visual content.
      placeholder: Add links to your works for written content here.
    validations:
      required: true
  - type: textarea
    id: recorded-content
    attributes:
      label: Recorded content in the past quarter
      description: Share with us the link(s) to any channels where you have produced or contributed to any of the followings in the past quarter. \n      - More than one technical-focused videos on own Youtube (or other platform) or podcast channel. \n      - Any Polkadot-focused YouTube (or other platform) channel or podcast where you were a guest speaker.
      placeholder: Add links to Youtube or podcast channel(s) here.
    validations:
      required: true
  - type: textarea
    id: public-speaking
    attributes:
      label: Public speaking
      description: Share with us the link(s) to any occasions when you served as a speaker or panelist at conferences or events on Polkadot-related topic(s) in the past quarter.
      placeholder: Add links to the event(s) here.
    validations:
      required: true
  - type: textarea
    id: event-organization
    attributes:
      label: Organization of or participation at Polkadot-related tech focused events
      description: Share with us the link(s) to any Polkadot-related tech focused events that you have organized or participated at in the past quarter. \n      - Any Polkadot related technical community meetup(s) organized or hosted.\n     - Any Polkadot related technical workshops organized or hosted.\n     - Any other community initiative(s) (e.g Polkadot-focused hackathon or coding challenge) organized or hosted.\n     - Any a Polkadot hackathon(s) where you served as a judge or a mentor. 
      placeholder: Add links to the event(s) here.
    validations:
      required: true
  - type: textarea
    id: active-involvement
    attributes:
      label: Active involvement in Polkadot based projects
      description: Share with us the link(s) to any groups or projects that you have been actively involved with, such as the followings.\n      - Founded or lead Polkadot-related working group or special interest group. \n     - Any Polkadot-based project where you are holding an engineering leadership position.  
      placeholder: Add links to group(s) or project(s) here.
    validations:
      required: true
  - type: textarea
    id: online-discussions
    attributes:
      label: Leading discussions in the online space
      description: Share with us link(s) to any channels in the online space where you are running and/or managing a Polkadot-focused media outlet or publication. 
      placeholder: Add links to your publication(s) here.
    validations:
      required: true
