name: Add comment to new Hero nomination
on:
  issues:
    types:
      - labeled
  workflow_dispatch:
  
jobs:
  add-comment:
    if: (github.event_name == 'workflow_dispatch') || (github.event.label.name == 'nomination')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for submitting a nomination for Hero status! :sparkles:

            A word about the process:

            The team reviews nominations on a rolling basis.
            We commit to reviewing every nomination within two weeks after the nomination has been submitted.

            As a reminder, the criteria for review and selection for Hero status is publicly available in this [GitHub repository](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md).

            You can continue to update your nomination form with new and relevant information up until the point of review.
            
            Have any questions? Please don't hesitate to [send us a message](mailto:heroes@parity.io)! :email:
