name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '44 14 * * *'
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This pull request has been inactive for quite some time. Are you still working on this?'
        stale-pr-label: 'no-pr-activity'
        close-pr-label: 'closed-pr-no-activity'
        days-before-issue-stale: 120
        days-before-pr-stale: 7
        days-before-pr-close: 14
        remove-pr-stale-when-updated: true
